<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin · <?= tt_h($siteName) ?></title><link rel="stylesheet" href="assets/app.css"><style>:root{--accent:<?= tt_h($accent) ?>}</style></head>
<body class="admin-page"><header class="admin-header"><div><p class="eyebrow">TEA &amp; TOAST</p><h1>Admin</h1></div><?php if (isset($_GET['embed'])): ?><button type="button" class="button" onclick="window.parent.postMessage({type:'tea-toast-close-admin'},window.location.origin)">Back to player</button><?php else: ?><a class="button" href="./">Back to player</a><?php endif; ?></header><main class="admin-grid">
<?php if ($error): ?><div class="alert error wide"><?= tt_h($error) ?></div><?php endif; ?><?php if ($notice): ?><div class="alert success wide"><?= tt_h($notice) ?></div><?php endif; ?>
<section class="card wide"><h2>Libraries</h2><p class="muted">Each path is read directly. Nothing here creates a music catalogue.</p><div class="table"><?php foreach ($libraries as $library): ?><div class="table-row"><div><strong><?= tt_h($library['name']) ?></strong><small><?= tt_h($library['root_path']) ?></small></div><form method="post"><input type="hidden" name="csrf" value="<?= tt_h(tt_csrf_token()) ?>"><input type="hidden" name="action" value="toggle_library"><input type="hidden" name="id" value="<?= (int) $library['id'] ?>"><button class="button small"><?= (int) $library['enabled'] ? 'Disable' : 'Enable' ?></button></form></div><?php endforeach; ?></div><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?= tt_h(tt_csrf_token()) ?>"><input type="hidden" name="action" value="add_library"><label>Library name<input name="name" required></label><label>Absolute NAS path<input name="root_path" placeholder="/volume1/Music" required></label><button class="button primary">Add library</button></form></section>
<section class="card"><h2>Users</h2><div class="table"><?php foreach ($users as $user): ?><div class="table-row"><div><strong><?= tt_h($user['display_name']) ?></strong><small><?= tt_h($user['email']) ?> · <?= tt_h($user['role']) ?></small></div><?php if ((int) $user['id'] !== (int) $currentUser['id'] && $user['role'] !== 'super_admin'): ?><form method="post"><input type="hidden" name="csrf" value="<?= tt_h(tt_csrf_token()) ?>"><input type="hidden" name="action" value="toggle_user"><input type="hidden" name="id" value="<?= (int) $user['id'] ?>"><button class="button small"><?= (int) $user['active'] ? 'Disable' : 'Enable' ?></button></form><?php endif; ?></div><?php endforeach; ?></div></section>
<section class="card"><h2>Create user</h2><form method="post"><input type="hidden" name="csrf" value="<?= tt_h(tt_csrf_token()) ?>"><input type="hidden" name="action" value="create_user"><label>Name<input name="display_name" required></label><label>Email<input type="email" name="email" required></label><label>Temporary password<input type="password" name="password" minlength="8" required></label><label>Role<select name="role"><option value="user">User</option><option value="admin">Administrator</option></select></label><button class="button primary">Create user</button></form></section>
<section class="card wide"><h2>Player settings</h2><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?= tt_h(tt_csrf_token()) ?>"><input type="hidden" name="action" value="settings"><label>Site name<input name="site_name" value="<?= tt_h($siteName) ?>" required></label><label>Accent colour<input type="color" name="accent_colour" value="<?= tt_h($accent) ?>"></label><label class="check"><input type="checkbox" name="registration_enabled" <?= $registrationEnabled ? 'checked' : '' ?>> Allow public registration</label><button class="button primary">Save settings</button></form></section>
</main></body></html>
